{ Log filtering: CASTLE_DOOM_LOG=Load,Music,Shot writes a second log,
  castle-doom-filtered.log in the user config directory (next to the
  saves; CASTLE_DOOM_LOG_FILE=path for another place), with only the
  lines of those categories (the text before the first ": ", e.g. "Load:
  E1M1: map parsed"), every warning and the lines that continue a kept
  line (multi-line messages like the profiler's tree). CGE's log has no
  filter, and its generated CastleAutoGenerated unit starts the log
  before any game code runs, so the full log stays as it was; the
  filtered copy is fed from ApplicationProperties.OnLog. Desktop only. }
unit GameLogFilter;

interface

uses Classes;

type
  { Passes whole lines from the log to Target when LogLineKept says so. }
  TLogFilterStream = class(TStream)
  strict private
    FTarget: TStream;
    FOwnsTarget: Boolean;
    FCategories: TStringList;
    FLine: String;
    FKeep: Boolean;
    procedure EmitLine(const Line: String);
  public
    { Categories: comma-separated, case-insensitive. }
    constructor Create(const ATarget: TStream; const AOwnsTarget: Boolean;
      const ACategories: String);
    destructor Destroy; override;
    function Write(const Buffer; Count: Longint): Longint; override;
    function Read(var Buffer; Count: Longint): Longint; override;
    function Seek(const Offset: Int64; Origin: TSeekOrigin): Int64; override;
  end;

{ The category of a log line ("Load" for "Load: E1M1: ..."; "Warning"
  for "Warning: Music: ..."), '' when the line has none (a header or a
  continuation line). }
function LogLineCategory(const Line: String): String;

{ Whether the filter keeps this line: warnings always, lines of the
  listed categories, and lines without a category as the previous one. }
function LogLineKept(const Line: String; const Categories: TStrings;
  const PreviousKept: Boolean): Boolean;

{ Start the filtered log when CASTLE_DOOM_LOG is set. }
procedure StartLogFilter;

implementation

uses SysUtils,
  CastleLog, CastleUriUtils, CastleApplicationProperties;

type
  TLogFilter = class
    Stream: TLogFilterStream;
    destructor Destroy; override;
    procedure Log(const Message: String);
  end;

var
  Filter: TLogFilter;

destructor TLogFilter.Destroy;
begin
  ApplicationProperties.OnLog.Remove({$ifdef FPC}@{$endif} Log);
  FreeAndNil(Stream);
  inherited;
end;

procedure TLogFilter.Log(const Message: String);
begin
  if Message <> '' then
    Stream.WriteBuffer(Message[1], Length(Message));
end;

function LogLineCategory(const Line: String): String;
var
  P, I: Integer;
begin
  Result := '';
  P := Pos(': ', Line);
  if P <= 1 then Exit;
  for I := 1 to P - 1 do
    if not (Line[I] in ['A'..'Z', 'a'..'z', '0'..'9', '_']) then
      Exit;
  Result := Copy(Line, 1, P - 1);
end;

function LogLineKept(const Line: String; const Categories: TStrings;
  const PreviousKept: Boolean): Boolean;
var
  Category: String;
begin
  Category := LogLineCategory(Line);
  if Category = '' then
    Result := PreviousKept
  else
    Result := SameText(Category, 'Warning') or (Categories.IndexOf(Category) >= 0);
end;

constructor TLogFilterStream.Create(const ATarget: TStream; const AOwnsTarget: Boolean;
  const ACategories: String);
begin
  inherited Create;
  FTarget := ATarget;
  FOwnsTarget := AOwnsTarget;
  FCategories := TStringList.Create;
  FCategories.CaseSensitive := false;
  FCategories.StrictDelimiter := true;
  FCategories.Delimiter := ',';
  FCategories.DelimitedText := StringReplace(ACategories, ' ', '', [rfReplaceAll]);
  { The header ("Log for ...", the version lines) is kept. }
  FKeep := true;
end;

destructor TLogFilterStream.Destroy;
begin
  if FLine <> '' then
    EmitLine(FLine);
  FreeAndNil(FCategories);
  if FOwnsTarget then
    FreeAndNil(FTarget);
  inherited;
end;

procedure TLogFilterStream.EmitLine(const Line: String);
var
  S: String;
begin
  FKeep := LogLineKept(Line, FCategories, FKeep);
  if FKeep then
  begin
    S := Line + LineEnding;
    FTarget.WriteBuffer(S[1], Length(S));
  end;
end;

function TLogFilterStream.Write(const Buffer; Count: Longint): Longint;
var
  Chunk: String;
  P: Integer;
begin
  Result := Count;
  if Count <= 0 then Exit;
  SetString(Chunk, PChar(@Buffer), Count);
  FLine := FLine + Chunk;
  repeat
    P := Pos(#10, FLine);
    if P = 0 then Break;
    EmitLine(TrimRight(Copy(FLine, 1, P - 1)));
    Delete(FLine, 1, P);
  until false;
end;

function TLogFilterStream.Read(var Buffer; Count: Longint): Longint;
begin
  Result := 0;
end;

function TLogFilterStream.Seek(const Offset: Int64; Origin: TSeekOrigin): Int64;
begin
  Result := 0;
end;

procedure StartLogFilter;
var
  Categories, FileName: String;
  Target: TStream;
begin
  Categories := GetEnvironmentVariable('CASTLE_DOOM_LOG');
  {$ifdef WASI}
  Categories := '';
  {$endif}
  if (Categories = '') or (Filter <> nil) then Exit;
  FileName := GetEnvironmentVariable('CASTLE_DOOM_LOG_FILE');
  if FileName = '' then
    FileName := UriToFilenameSafe('castle-config:/castle-doom-filtered.log');
  if FileName = '' then Exit;
  try
    ForceDirectories(ExtractFileDir(FileName));
    Target := TFileStream.Create(FileName, fmCreate or fmShareDenyNone);
  except
    on E: Exception do
    begin
      WritelnWarning('Log', 'Cannot create the filtered log %s: %s', [FileName, E.Message]);
      Exit;
    end;
  end;
  Filter := TLogFilter.Create;
  Filter.Stream := TLogFilterStream.Create(Target, true, Categories);
  ApplicationProperties.OnLog.Add({$ifdef FPC}@{$endif} Filter.Log);
  WritelnLog('Log', 'Categories %s (CASTLE_DOOM_LOG) also go to %s', [Categories, FileName]);
end;

finalization
  FreeAndNil(Filter);
end.
